- id: "/"
  title: "Sezione Giovani"
  description: "Sezione Giovani del Congresso SIF 2021"
  keywords: "aisf associazione italiana studenti di fisica iaps tiqit trento innsbruck quantum information tour"
